app = 'amneszia-backend'
primary_region = 'cdg'

[build]
build-target = "production"

[env]
NETWORK = "mainnet"

[processes]
game = "./game"


[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['game']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
